2016-06-02 17:28:26,272: ERROR: api.py: update_delete_user():126: Error occured while deletinguser record 2: 'NoneType' object has no attribute 'user'
2016-06-02 17:28:26,273: ERROR: app.py: server_error():42: error code = 500
2016-06-02 17:28:26,274: ERROR: app.py: server_error():45: error desc = 'NoneType' object has no attribute 'user'
